### ISSUE TITLE
Option to insert Disqus

### ISSUE THREAD

**Issue by gaow** [bookdown/Bookdown.Bookdown#43]
Is there a plan to allow for inserting Disqus section to HTML pages? A particular user case that motivates the request is to create via bookdown a lab notebook to organize daily research, where analysis procedures are published allowing for random comments be made by colleagues on the same page under the Disqus section.

Thank you!

**Comment by pmjones** [comment]
I had not thought of it, but that's a great idea. If you want to send a PR for it, that would be awesome; otherwise it will have to wait until someone has time.

**Comment by sandrokeil** [comment]
Good idea, but I see some problems. We have to create a new bookdown.json file config section _disqus_, which is not a problem. We should also support the other Disqus options. 

But we need an [unique id for every page](https://help.disqus.com/customer/portal/articles/472098-javascript-configuration-variables) on which the comments relies on. If the name of the page has changed, the id should be the same, otherwise the comments are lost. How does this work with multi books?

_Feature request:_
Only load comments/js if you click on a button e.g. "discuss" and display number of comments somewhere.

**Comment by pmjones** [comment]
Closing this, as there has been no movement on it. Please re-open as needed, or (preferably) send a PR.
